### PR TITLE
DBZ-1043 Upgrade to Confluent 5.1.0

### PR DESCRIPTION
**Pull request by renatomefi**
https://issues.jboss.org/browse/DBZ-1043

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Applied; thanks, @renatomefi!

**Comment by gunnarmorling** [comment]
i think we should revert that change due to the regression revealed by the PR in the main repo, https://github.com/debezium/debezium/pull/712.

**Comment by jpechane** [comment]
@gunnarmorling I agree, also the change is incomplete as hashes for the files were not updated so the Docker builds fails.

**Comment by gunnarmorling** [comment]
I've reverted that change.

**Comment by renatomefi** [comment]
Indeed, thanks for it!

**Comment by ankit45621** [comment]
Hello everyone,

I am facing similar issue with confluent image version 5.1.0 at https://github.com/ivangfr/springboot-kafka-debezium-ksql/issues/4:

org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:269)
at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:293)
at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:228)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.avro.AvroRuntimeException: Unknown datum class: class java.lang.Short
at org.apache.avro.util.internal.JacksonUtils.toJson(JacksonUtils.java:87)
at org.apache.avro.util.internal.JacksonUtils.toJsonNode(JacksonUtils.java:48)
at org.apache.avro.Schema$Field.(Schema.java:423)
at org.apache.avro.Schema$Field.(Schema.java:415)
at io.confluent.connect.avro.AvroData.addAvroRecordField(AvroData.java:964)
at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:847)
at io.confluent.connect.avro.AvroData.fromConnectSchemaWithCycle(AvroData.java:942)
at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:834)
at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:689)
at io.confluent.connect.avro.AvroData.fromConnectSchema(AvroData.java:683)
at io.confluent.connect.avro.AvroData.fromConnectData(AvroData.java:328)
at io.confluent.connect.avro.AvroConverter.fromConnectData(AvroConverter.java:76)
at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:269)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
... 11 more



Anyone please help me with issue at https://github.com/ivangfr/springboot-kafka-debezium-ksql/issues/4

**Comment by jpechane** [comment]
@ankit45621 Hi, you need to upgrade the Confluent - see https://github.com/confluentinc/schema-registry/issues/968

**Pull request merged**
