### PR TITLE
[DBZ-507] Add PostGIS 2.4 to PostgreSQL images

### PR DESCRIPTION
**Pull request by rcoup**
For PostGIS support in https://github.com/debezium/debezium/pull/374

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@rcoup Could you prefix the commit message with "DBZ-507 ..."? Thx!

**Comment by rcoup** [comment]
@gunnarmorling done.

**Comment by jpechane** [comment]
Hmm, do we want to add postgis by default or will we have two images one with and one without - see https://issues.jboss.org/browse/DBZ-445

**Comment by rcoup** [comment]
_Surely_ nobody is using the "Debezium" Postgres image in the real world to run their actual database? 

And if they _are_ (there's always one!) then TBH they probably don't care about 200MB — it's not like this image will be pulled onto a cluster 10x a day like an application image would be...

**Comment by jpechane** [comment]
Merged, thanks!

**Pull request merged**
