### PR TITLE
Potential fix for hypen-containing environment variables: DBZ-3019

### PR DESCRIPTION
**Pull request by mrshanepaul**
Please refer to: https://issues.redhat.com/browse/DBZ-3019

As requested in the issue commentary, a change for this script.
 
I imagine a bash guru could optimize the value extraction of this code into a single line. 
I have changed the log4j creation code for completion, but this is likely unnecessary due to the constraints on package names.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, could you review this one? Thx!

**Comment by jpechane** [comment]
@mrshanepaul Applied, thanks a lot. I've just edited the commit message and copied the fix to 1.5 too. Works like a charm!

**Comment by mrshanepaul** [comment]
You are most welcome @jpechane, glad I could contribute.

**Comment by wadesherman** [comment]
Small regression here: This truncates values at the first space.

**Comment by jpechane** [comment]
@wadesherman Thanks! Could you please raise a Jira issue with description and exmaple of the problem?

**Comment by wadesherman** [comment]
@jpechane 
https://issues.redhat.com/browse/DBZ-3103

**Pull request merged**
