### PR TITLE
DBZ-1542 Support for Postgres 12 images

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-1542

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, there's a failure for PG 11?

**Comment by jpechane** [comment]
@gunnarmorling The postgis in Debian package has a broken dependency so we have to wait till it is fixed

**Comment by jpechane** [comment]
@gunnarmorling The package has been repaired so the build is passing again

**Comment by gunnarmorling** [comment]
Applied; thanks, @jpechane!

**Pull request merged**
