### PR TITLE
upgrading docker containers to jdk11. DBZ-969.

### PR DESCRIPTION
**Pull request by brbrown25**
@gunnarmorling not sure if there is anything else needed for this/if you'd prefer me to place these changes in a different version directory?

### CODE REVIEW

**Comment by Naros** [comment]
I think we should consider adding some `1.0` directories and making the Dockerfile changes relative to the `1.0` tag rather than adjusting the `0.10` version.  @gunnarmorling wdyt?

**Comment by jpechane** [comment]
@Naros I almost agree ;-)
@brbrown25 Could you please rebase the PR to the latest master? With the last week release the `1.0` directories has been created. Could you please extend the PR to modify *both* `0.10` and `1.0` images?

Thanks

**Comment by brbrown25** [comment]
> @Naros I almost agree ;-)
> @brbrown25 Could you please rebase the PR to the latest master? With the last week release the `1.0` directories has been created. Could you please extend the PR to modify _both_ `0.10` and `1.0` images?
> 
> Thanks

Yep I will make those changes!

- [ ] rebase

- [ ] apply changes to 1.0 and 0.10

- [ ]

**Comment by gunnarmorling** [comment]
After discussing more with @renatomefi offline, it seems that UBI isn't the ideal fit for our needs here, as this would limit extensibility of the container images. So my preference and suggestion would be to base them on Fedora and simply install the provided OpenJDK packages. Then people are free to add any other Fedora packages in derived images.

**Comment by jpechane** [comment]
Let's not forget about registry.fedoraproject.org/fedora-minimal:30

**Comment by jpechane** [comment]
I've just tried in the minimal image
```
cat <<EOF > /etc/yum.repos.d/adoptopenjdk.repo
[AdoptOpenJDK]
name=AdoptOpenJDK
baseurl=http://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/centos/7/$(uname -m)
enabled=1
gpgcheck=1
gpgkey=https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
EOF

microdnf install adoptopenjdk-11-hotspot
```

and I have working OpenJDK 11

The minimal image size is 142 MB, the image size with OpenJDK installed is roughly 450 MB. - The JVM dir itself contains 314 MB.

So we might create a Debezium base Java image (we had in the past) and build upon it

**Comment by renatomefi** [comment]
@gunnarmorling indeed the UBI situation is tricky!

@jpechane I like the idea going to Fedora + OpenJDK, I'd say we don't even need a base java image, we could have our base Kafka image already shipping the jdk + kafka itself, we can potentially reduce maintenance and amount of layers!

I like this path!

**Comment by jpechane** [comment]
@renatomefi Don't forget about ZooKeeper. It needs Java as well so it makes sense to have a separate Java base image

**Comment by gunnarmorling** [comment]
@jpechane, is there any specific reason for using AdoptOpenJDK? Fedora has its own package for OpenJDK, can't we take this?

**Comment by jpechane** [comment]
@gunnarmorling I am not 100 % sure but I think there is still openjdk 8

**Comment by gunnarmorling** [comment]
There's both, e.g. here for OpenJDK 11:
https://fedora.pkgs.org/30/fedora-updates-x86_64/java-11-openjdk-11.0.5.10-0.fc30.x86_64.rpm.html

**Comment by renatomefi** [comment]
> @renatomefi Don't forget about ZooKeeper. It needs Java as well so it makes sense to have a separate Java base image

@jpechane you're right, I was thinking from the perspective we ship only KC, assuming people already have a Kafka cluster running, but yes, it makes sense to have a base in this case!

@gunnarmorling and what would be the reasons for not going with adoptopenjdk one? I'm just curious since we've been using it here quite often!

**Comment by gunnarmorling** [comment]
Yes, no need for configuring another repo when using the Fedora one. But more importantlyy, those are tested (and pass) the Java TCK, whereas AdoptOpenJDK binaries are not TCK-certified.

**Comment by gunnarmorling** [comment]
@renatomefi, regarding

> what would be the reasons for not going with adoptopenjdk one? I'm just curious since we've been using it here quite often!

A few reasons:

* Not TCK-verified
* We'd have to abandon the RHEL/CentOS/Fedora universe, which is quite disruptive for folks deriving from our images; as discussed, the UBI option they have isn't suitable for us in regards to exensibility

So my thought was to simply install the openjdk 11 package on CentOS. But then I realized that's pretty much what the Fabric8 image is doing. So indeed I think the proposed change here in this PR is what I'd like to apply. It gives JDK 11 on CentOS, meaning the upgrade to users will be smooth hopefully.

**Comment by gunnarmorling** [comment]
Closing in favour of https://github.com/debezium/docker-images/pull/155, where only the 1.0 images are updated. Thanks a lot everybody! I'm going with the simple version upgrade for now; the potential change to a different base image is tracked via https://issues.jboss.org/browse/DBZ-1308. We should make up our minds on that one for 1.0.

**Pull request closed without merging**
