### PR TITLE
DBZ-3245 Catch first equal sign while separating key/value

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-3245

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, any thoughts on the build failure ("username/password wrong")?

**Comment by jpechane** [comment]
Yes,there's one problem. We need login to bypass Hub rate limiting. But PRs form unrelated repos cannot access the secrets :-(.
There is really no good solution fo that

**Comment by gunnarmorling** [comment]
Ok, I see. so the issue shouldn't occur on master then, right?

**Comment by jpechane** [comment]
Right, I wonder if it makes sense to have authenticated builds for master and unauthenticated for PRs?

**Comment by gunnarmorling** [comment]
If we can, why not. IIUC, it'd at least increase odds for PR builds to succeed, if they don't run into the rate limit.

**Pull request merged**
