### PR TITLE
Use ARG with defaults for Kafka's versions and sha

### PR DESCRIPTION
**Pull request by frankkoornstra**
Debezium's Dockerfile creates a nice clean Kafka image that we like to base our image on but has a small issue: the versions and the sha512 hash are created as environment variables which cannot be manipulated during docker build time (except maybe by regex replaces). 

This PR changes that by moving them to `ARG` with the same defaults and setting the `ENV`s from those build arguments. The behavior therefore stays exactly the same but it does allow users of this Dockerfile to inject different versions if need be.

### CODE REVIEW

**Comment by jpechane** [comment]
Hi, good idea, thanks for PR. Could you please create a Jira issue and reword the commit to be `DBZ-xxx Use ARG with defaults for Kafka's versions and sha`?

**Comment by gunnarmorling** [comment]
Interesting; I'm ok with this change, but we should clarify that any given Debezium version has only been tested with the default Kafka version of that release's Debezium image. I.e. there'd be no guarantees that Debezium could be used with another version (in practice, I think chances for problems are very low, but we should properly manage expectations).

**Comment by frankkoornstra** [comment]
>Could you please create a Jira issue and reword the commit to be DBZ-xxx Use ARG with defaults for Kafka's versions and sha?

My bad, I couldn't find the contributing docs in this repo but realized they're [in the main repo](https://github.com/debezium/debezium/blob/master/CONTRIBUTE.md#making-changes). I'll create that ticket and reword the commit title.

>we should clarify that any given Debezium version has only been tested with the default Kafka version of that release's Debezium image. I.e. there'd be no guarantees that Debezium could be used with another version (in practice, I think chances for problems are very low, but we should properly manage expectations).

I could add some comment above the `ARG` lines saying exactly this. Any suggestions on the wording? Proposal
>These arguments can be overruled during build time but compatibility cannot be guaranteed when these defaults are not used.

**Comment by jpechane** [comment]
@frankkoornstra Good for me! Just please either squash the commits or add the DBZ-2323 prefix to the message of the first commit

**Comment by gunnarmorling** [comment]
Applied. Thanks, @frankkoornstra!

@jpechane, you also can squash commits yourself right here in the UI, allowing to combine commit messages as needed and preserving original authorship.

**Comment by frankkoornstra** [comment]
Awesome! Thanks for the help

**Comment by gunnarmorling** [comment]
Thank *you* for you contribution :)

**Pull request merged**
