### PR TITLE
DBZ-893 Added other environment variables in entrypoint

### PR DESCRIPTION
**Pull request by shivamsharma**
1. Added status storage topic and made it mandatory
2. Added replication & partition for topics in dockerfile to make it consistent

### CODE REVIEW

**Comment by shivamsharma** [comment]
@gunnarmorling Please review

**Comment by gunnarmorling** [comment]
@jpechane Any objections from your side? The only thing we should do is to clarify the new mandatory option in the change log of 0.9-next.

**Comment by jpechane** [comment]
@gunnarmorling I think I've already voiced my concerns elsewhere. Regarding this PR, I think it is very unwise to introduce a *mandator* env variable. Environment variables are a form contract or interface of Docker image so the result is the same as if you modify a method signature of an interface that has to be implemented by the client code - it immediately breaks clients and make migration more difficult. If we introduce a *mandatory* parameter we will break all ops scripts around the world that use our images.

I agree with introduction of `STATUS_STORAGE_TOPIC` to provide a symmetry to `OFFSET_STORAGE_TOPIC` but I believe that the rest of the parameters should stay in form of `CONNECT_*` names.

**Comment by gunnarmorling** [comment]
@jpechane Ok, I first understood you'd consider such breaking change (which it is indeed) as acceptable for a new minor (=0.9). So you'd prefer `STATUS_STORAGE_TOPIC` to remain optional then?

> but I believe that the rest of the parameters should stay in form of CONNECT_* names.

Why is this? I.e. where should we draw the line? Unfortunately the whole situation is a bit messy, but I think it'd be easier to comprehend if we allowed those vars to be given without the prefix (note they'd still be able to be given _with_ the prefix in any case).

**Comment by jpechane** [comment]
@gunnarmorling I'd avoid introducing any new env var that is just passthrough to the `CONNECT_` var. Only if some parsing/manipulation is assocaited with it then it would make sense to intorduce a new var. The `STATUS_STORAGE_TOPIC` is an exception because there is existing counterpart. And you are right, I prefer it to be an optional one.

**Comment by gunnarmorling** [comment]
Ok then. I'll adjust the PR accordingly and merge.

**Comment by shivamsharma** [comment]
@gunnarmorling Just let me know If you require any further changes!!!

**Comment by shivamsharma** [comment]
Any update on this. It is already more than a month. Should we close this request?

**Comment by gunnarmorling** [comment]
@shivamsharma Finally getting back to this; sorry for the delay.

**Comment by gunnarmorling** [comment]
Superseded by #103. I've added one more commit to make STATUS_STORAGE_TOPIC optional (a warning will be printed if it's not given) and remove the replication/partition related options, as they can be given with the CONNECT_ prefix.

Thanks for your contribution and your patience, @shivamsharma! The change will be part of the next 0.9.x release (planned for the next few days)

**Comment by shivamsharma** [comment]
@gunnarmorling Thanks. I want to contribute more in the future specifically in core Debezium.

**Pull request closed without merging**
