### PR TITLE
DBZ-3944 Fix for incorrect syntax in MySQL 8.0 example image💉

### PR DESCRIPTION
**Pull request by d3vel0per**
https://issues.redhat.com/browse/DBZ-3944

Below 2 lines from `examples/mysql/1.7/inventory.sql` are non compliant with MySQL 8.0 syntax
```sql
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'replicator' IDENTIFIED BY 'replpass';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'debezium' IDENTIFIED BY 'dbz';
```

this is because `GRANT` syntax in 8.0 no more accepts auth_options as it was in 5.7
```
auth_option: {
    IDENTIFIED BY 'auth_string'
  | IDENTIFIED WITH auth_plugin
  | IDENTIFIED WITH auth_plugin BY 'auth_string'
  | IDENTIFIED WITH auth_plugin AS 'auth_string'
  | IDENTIFIED BY PASSWORD 'auth_string'
}
```

This is now exclusive to `CREATE` statements only.
I see the image was recently updated. This prevents the image with defaults to start successfully.

References:
https://dev.mysql.com/doc/refman/5.7/en/grant.html
https://dev.mysql.com/doc/refman/8.0/en/grant.html

### CODE REVIEW

**Comment by jpechane** [comment]
@d3vel0per Hi, thanks for the PR, the issue is hadnled in https://github.com/debezium/docker-images/pull/242/commits/3b13707e90f807df9d87c5c8b457121d99a33420 waiting for merge.

**Comment by d3vel0per** [comment]
@jpechane Ahh!! Apologies I only checked the open PR's

**Comment by gunnarmorling** [comment]
Hey @d3vel0per, welcome to the project!

> Are there any contributor guidelines because I dont see issues but there are issue identifiers like DBZ-XXXX

Contribution guidelines are [here](https://github.com/debezium/debezium/blob/master/CONTRIBUTE.md); issue are tracked in Jira, this issue has already been logged as [DBZ-3944](https://issues.redhat.com/browse/DBZ-3944).

> Whats the other branch which is still kept on 5.7 ie. mysql-gtids?

Good point, I think we should upgrade it too. @jpechane?

> the issue is hadnled in 3b13707 waiting for merge.

@jpechane, I'd say let's go with this PR here (just changing the commit message to refer to DBZ-3944), as yours needs some more discussion re the base image choice, and this shouldn't block to fix the example image.

**Comment by jpechane** [comment]
@gunnarmorling I don't think we need to touch 5.7 as for it the DDL is perfectly valid.
Also check the referred commit there is one more change added to MySQL config file required for authentication.

**Comment by gunnarmorling** [comment]
>  I don't think we need to touch 5.7 as for it the DDL is perfectly valid

Should we update the GTID image to 8.0 though?

**Comment by jpechane** [comment]
@gunnarmorling Yes, of course! Also the config file.

**Comment by d3vel0per** [comment]
@jpechane @gunnarmorling I have updated the PR based on commentary.
Feel free to close this based on the existing workflows.

Cheers!

**Comment by gunnarmorling** [comment]
Applied; thx, @d3vel0per!

**Pull request merged**
