### PR TITLE
DBZ-3939 Migrate to UBI image from Fabric8

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-3939
https://issues.redhat.com/browse/DBZ-3944

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Interesting you went with UBI instead of Fedora. When we discussed this a while ago with @renatomefi, we concluded that UBI isn't an ideal basis, because it restricts what people can add themselves in downstream images. I feel using UBI may be reevaluated for Debezium 2.0, but for now using Fedora Minimal Base would definitely be less disruptive. WDYT?

**Comment by jpechane** [comment]
As I mentioned in the Jira. We already use it for Debezium Server. I am fine with either option. The most important for me was to confirm/deny whether the UBI is feasible.

If we go with Fedora then I propose we must provide our own common Java image (as we had in the past) on which the other images will be based. The main reason is that Fedora is released frequently so we would need to update only a single image, not multiple ones.

One more question, how about CentOS stream?

**Comment by gunnarmorling** [comment]
After discussing some more offline, let's go for Fedora Minimal Base, with a common Java base image for all the Debezium images.

**Comment by jpechane** [comment]
@gunnarmorling Rebase on Fedora

**Review by gunnarmorling — APPROVED** [review]

**Pull request merged**
